### ISSUE TITLE
Error when entering the world

### ISSUE THREAD

**Issue by wiselder** [magneticflux-/fabric-mumblelink-mod#35]
https://github.com/magneticflux-/fabric-mumblelink-mod/blob/1b81ca2536ef67adce2116db2b9fdb147a86ce46/src/main/kotlin/com/skaggsm/mumblelinkmod/ClientMumbleLinkMod.kt#L48

`Failed to handle packet fabric-mumblelink-mod:broadcast_mumble_url!
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod.packetConsumer(ClientMumbleLinkMod.java:48)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod.access$packetConsumer(ClientMumbleLinkMod.java:35)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod$onInitializeClient$1.invoke(ClientMumbleLinkMod.java:56)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod$onInitializeClient$1.invoke(ClientMumbleLinkMod.java:35)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkModKt$sam$net_fabricmc_fabric_api_network_PacketConsumer$0.accept(ClientMumbleLinkModKt.java)
	at net.fabricmc.fabric.impl.networking.PacketRegistryImpl.accept(PacketRegistryImpl.java:192)
	at net.minecraft.class_634.handler$zzc000$onCustomPayload(class_634.java:2482)
	at net.minecraft.class_634.method_11152(class_634.java)
	at net.minecraft.class_2658.method_11457(class_2658.java:65)
	at net.minecraft.class_2658.method_11054(class_2658.java:10)
	at net.minecraft.class_2535.method_10759(class_2535.java:158)
	at net.minecraft.class_2535.method_10770(class_2535.java:149)
	at net.minecraft.class_2535.channelRead0(class_2535.java:54)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by wiselder** [comment]
the only error I see in the logs.
positioning doesn't work on the mumble server

**Comment by wiselder** [comment]
when connecting to the minecraft server, there is no such error, it is written in the log, but there were no notifications about communication in the minecraft chat and the mumble chat
![изображение](https://user-images.githubusercontent.com/51117739/101204660-9dbaa980-367d-11eb-89ca-b4643c0acee2.png)

**Comment by magneticflux-** [comment]
I guess this is resolved? It all happened while I was asleep lol.

The error means that the desktop environment you're using doesn't support opening browsers for some reason. This would prevent automatic channel joining on server and dimension changes, but shouldn't affect positioning once you're in the same channel as someone else.
