### ISSUE TITLE
Prevented from joining server if BROWSE action does not work

### ISSUE THREAD

**Issue by Veyrdite** [magneticflux-/fabric-mumblelink-mod#51]
I get a 'connection lost' screen in my client shortly after trying to connect to the server.  I never get as far as seeing the in-game world.  Completely blocks me.  Possibly similar to #35

* Mumblelink 0.7.5
* Fabric loader 0.11.1
* MC 1.16.5
* Linux 5.10.8_1
* openjdk version "1.8.0_272"

I'm not using a full-blown desktop environment, I'm instead using a standalone window manager (i3wm) and my own collection of programs.  I've never had issues like this before, stuff like xdg-open works fine.

Maybe I have a missing protocol (eg mumble://) in my conf file?

My config (on the server side):
```
mumbleAutoLaunchOption = "ACCEPT"
mumbleDimensionYAxisAdjust = 0.0
voipClient = "MUMBLE"
mumbleServerHost = "my.domain.of.evil"
mumbleServerPort = 64738
```

Errors in client:
```
[20:27:01] [Netty Epoll Client IO #0/ERROR]: Encountered exception while handling in channel with name "fabric-mumblelink-mod:broadcast_mumble_url"
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:221) ~[?:1.8.0_272]
	at java.awt.Desktop.browse(Desktop.java:380) ~[?:1.8.0_272]
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod.packetConsumer(ClientMumbleLinkMod.java:50) ~[fabric-mumblelink-mod-0.7.5.jar:?]
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod.access$packetConsumer(ClientMumbleLinkMod.java:35) ~[fabric-mumblelink-mod-0.7.5.jar:?]
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod$onInitializeClient$1.invoke(ClientMumbleLinkMod.java:58) ~[fabric-mumblelink-mod-0.7.5.jar:?]
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod$onInitializeClient$1.invoke(ClientMumbleLinkMod.java:35) ~[fabric-mumblelink-mod-0.7.5.jar:?]
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkModKt$sam$net_fabricmc_fabric_api_network_PacketConsumer$0.accept(ClientMumbleLinkModKt.java) ~[fabric-mumblelink-mod-0.7.5.jar:?]
	at net.fabricmc.fabric.impl.networking.ClientSidePacketRegistryImpl.lambda$register$0(ClientSidePacketRegistryImpl.java:65) ~[0568dc96-7ffd-4458-b738-b0d979971f00.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[d5dabcff-f3e3-4116-921b-62745ffebf8d.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[d5dabcff-f3e3-4116-921b-62745ffebf8d.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [d5dabcff-f3e3-4116-921b-62745ffebf8d.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) [d5dabcff-f3e3-4116-921b-62745ffebf8d.jar:?]
	at net.minecraft.class_634.handler$cid000$handleCustomPayload(class_634.java:2474) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:65) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:10) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:156) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:147) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) [intermediary-minecraft-1.16.5-client.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

**Comment by magneticflux-** [comment]
If you can't get the browse action working, you can always set your client's `mumbleAutoLaunchOption` to `IGNORE`. That will prevent the mod from trying to open URLs.

This may help debugging the browse action: https://www.reddit.com/r/i3wm/comments/85j800/links_calls_to_other_programs_not_working_for/

**Comment by magneticflux-** [comment]
I'll also make a note to print a big warning instead of crashing if the browse action doesn't work.

**Comment by Veyrdite** [comment]
Thankyou :)

Not familiar with the environment & language, but can you do a fallback call to something  equivalent to system() with one of these?  EDIT:

* mumble mumble://asdfsdf:port
* xdg-open mumble://asdfasdf:port

Both of these commands work for me.

**Comment by magneticflux-** [comment]
I'll address those in #52!
