### ISSUE TITLE
1.17 game crashing when joining a world

### ISSUE THREAD

**Issue by foxydre049** [magneticflux-/fabric-mumblelink-mod#70]
Hello thank you for updating the mod but I have an error when I join a server my game crash
Here is the crash log :
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 23/06/2021 10:15
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 438 out of bounds for char[256]
	at java.base/java.lang.System.arraycopy(Native Method)
	at com.skaggsm.jmumblelink.MumbleLinkImpl.setIdentity(MumbleLinkImpl.java:169)
	at com.skaggsm.mumblelinkmod.client.ClientMumbleLinkMod.setupEvents$lambda-6(ClientMumbleLinkMod.java:168)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zzm000$onStartTick(class_310.java:3068)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1083)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.System.arraycopy(Native Method)
	at com.skaggsm.jmumblelink.MumbleLinkImpl.setIdentity(MumbleLinkImpl.java:169)
	at com.skaggsm.mumblelinkmod.client.ClientMumbleLinkMod.setupEvents$lambda-6(ClientMumbleLinkMod.java:168)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zzm000$onStartTick(class_310.java:3068)
```

**Comment by magneticflux-** [comment]
What dimension are you in when joining?

**Comment by magneticflux-** [comment]
I have a fix on the way.

**Comment by magneticflux-** [comment]
A new release will be published when this run finishes: https://github.com/magneticflux-/fabric-mumblelink-mod/actions/runs/965604222
