### ISSUE TITLE
Incompatibility with multiple mods on macOS due to use of AWT classes

### ISSUE THREAD

**Issue by magneticflux-** [magneticflux-/fabric-mumblelink-mod#78]
The existing system needs to be expanded to include all mods on macOS.

See #31, #41

**Comment by Mask** [comment]
Note that (as in described in the comments of #31) the current implementation crashes/hangs on MacOS without any other mods - so it's not only a matter of interaction with other AWT-using mods

**Comment by magneticflux-** [comment]
@Mask Can you reproduce the crash in a development environment with a breakpoint placed on `java.awt.Toolkit.loadLibraries()` and show the stacktrace? I'd like to figure out which class is triggering the load.

The culprit I identified in Optifine are documented here: https://github.com/sp614x/optifine/issues/4980

Additionally, 80da3209bbba0a2e4de5ef41d7444e332331d2b9 should work around any more of these issues with other mods going forward. I plan to release this last patch for 1.17.x and then start on 1.18.

**Comment by Mask** [comment]
@magneticflux- using 48165f48653e1529e47ff2e339ad17c3dfaf9e5e 
I put a breakpoint on java.awt.Toolkit.loadLibraries() but it is never executed.
If I put a breakpoint on https://github.com/magneticflux-/fabric-mumblelink-mod/blob/3866317c64f9b7f5b9b4f17e88cd51c0a717b993/src/main/kotlin/com/skaggsm/mumblelinkmod/client/ClientMumbleLinkMod.kt#L194-L201 then I see an exception being thrown on `headlessField.isAccessible = true`:

```
Unable to make field private static java.lang.Boolean java.awt.GraphicsEnvironment.headless accessible: module java.desktop does not "opens java.awt" to unnamed module @7ffa6333

	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
	at com.skaggsm.mumblelinkmod.client.ClientMumbleLinkMod.ensureNotHeadless(ClientMumbleLinkMod.kt:198) ~[main/:?]
	at com.skaggsm.mumblelinkmod.client.ClientMumbleLinkMod.channelHandler(ClientMumbleLinkMod.kt:72) ~[main/:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[fabric-networking-api-v1-1.0.18+3ac43d95c8.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.0.18+3ac43d95c8.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [fabric-networking-api-v1-1.0.18+3ac43d95c8.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) [fabric-networking-api-v1-1.0.18+3ac43d95c8.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$zzo000$handleCustomPayload(ClientPlayNetworkHandler.java:2238) [minecraft-project-@-mapped.jar:?]
```

**Comment by magneticflux-** [comment]
Ah, whoops, that would do it. I'll avoid reflection and just special-case macOS then!
